
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import javax.swing.*;
public class Keyboard extends JFrame{
     JTextArea textarea=new JTextArea();
     public static Boolean cap = false;
     JFrame fram=new JFrame("keyboard");
     JPanel panel=new JPanel();
     JPanel panel1=new JPanel();
         JButton buttonESc=new JButton("ESC");
         JButton buttonE=new JButton("`");
         JButton button1=new JButton("1");
         JButton button2=new JButton("2");
         JButton button3=new JButton("3");
         JButton button4=new JButton("4");
         JButton button5=new JButton("5");
         JButton button6=new JButton("6");
         JButton button7=new JButton("7");
         JButton button8=new JButton("8");
         JButton button9=new JButton("9");
         JButton button0=new JButton("0");
         JButton buttonn=new JButton("-");
         JButton buttonnnn=new JButton("<--");
         JButton buttonnnnn=new JButton("C");
         JButton buttonnnnnn=new JButton("-->");
         JButton buttonnnnnnn=new JButton(".");
         JButton buttonnnnnnnn=new JButton("=");
         JButton buttonbackspace=new JButton("backspac");
         JButton buttontab=new JButton("tab");
         JButton buttonQ=new JButton("q");
         JButton buttonW=new JButton("w");
         JButton buttonEe=new JButton("e");
         JButton buttonR=new JButton("r");
         JButton buttonT=new JButton("t");
         JButton buttonY=new JButton("y");
         JButton buttonU=new JButton("u");
         JButton buttonI=new JButton("i");
         JButton buttonO=new JButton("o");
         JButton buttonP=new JButton("p");
         JButton butto=new JButton("[");
         JButton butt=new JButton("]");
         JButton but=new JButton("|");
         JButton buttonCapslock=new JButton("Caps lock        ");
         JButton buttonA=new JButton("a");
         JButton buttonS=new JButton("s");
         JButton buttonD=new JButton("d");
         JButton buttonF=new JButton("f");
         JButton buttonG=new JButton("g");
         JButton buttonH=new JButton("h");
         JButton buttonJ=new JButton("j");
         JButton buttonK=new JButton("k");
         JButton buttonL=new JButton("l");
         JButton bu=new JButton(";");
         JButton b=new JButton("'");
         JButton bt=new JButton("`");
         JButton buttonenter=new JButton("Enter                    ");
         JButton buttonshift=new JButton("shift                   ");
         JButton buttonZ=new JButton("z");
         JButton buttonX=new JButton("x");
         JButton buttonC=new JButton("c");
         JButton buttonV=new JButton("v");
         JButton buttonB=new JButton("b");
         JButton buttonN=new JButton("n");
         JButton buttonM=new JButton("m");
         JButton bb=new JButton(".");
         JButton bbb=new JButton(",");
         JButton bbbb=new JButton("/");
         JButton buttonShift=new JButton("Shift                  ");
         JButton bun=new JButton("^");
         JButton buttonctrl=new JButton("Ctrl");
         JButton buttonFn=new JButton("fn");
         JButton buttonalt=new JButton("alt");
         JButton buu=new JButton("                                             ");
         JButton buttonAlt=new JButton("alt");
         JButton buttonCtrl=new JButton("Ctrl");
         JButton buuu=new JButton("~");
         JButton bunn=new JButton(" ");        
         JButton buttonHome=new JButton("Home");
         JButton buttonPgUp=new JButton("PgUp");
         JButton buttonNav=new JButton("Nav");
         JButton buttonEnd=new JButton("End");
         JButton buttonPgDn=new JButton("PgDn");
         JButton buttonMvUp=new JButton("MvUp");
         JButton buttonInsert=new JButton("Insert");
         JButton buttonPause=new JButton("Pause");
         JButton buttonMvDn=new JButton("MvDn");
         JButton buttonPrtScn=new JButton("PrtScn");
         JButton buttonScrlK=new JButton("ScrlK");
         JButton buttonDocK=new JButton("DocK");
         JButton buttonOptions=new JButton("Options");
         JButton buttonHelp =new JButton("HelP");
         JButton buttonFade=new JButton("Fade");
         JButton buttonDel=new JButton("Del                 ");
         JButton bnnn=new JButton("  ");
    Keyboard(){
            myaction a=new myaction();
            myaction2 a2=new myaction2();
            buttontab.addActionListener(a2);
            myaction3 a3=new myaction3();
       buu.addActionListener(a3);
       buttonshift.addActionListener(a3);
       buttonShift.addActionListener(a3);
       buttonenter.addActionListener(a3);
       buttonbackspace.addActionListener(a3);
       buttonDel.addActionListener(a3);
       buttonCapslock.addActionListener(a3);
       buttonHome.addActionListener(a3);
       button1.addActionListener(a);
       button2.addActionListener(a);
       button3.addActionListener(a);
       button4.addActionListener(a);
       button5.addActionListener(a);
       button6.addActionListener(a);
       button7.addActionListener(a);
       button8.addActionListener(a);
       button9.addActionListener(a);
       button0.addActionListener(a);
       buttonn.addActionListener(a);
       buttonQ.addActionListener(a);
       buttonW.addActionListener(a);
       buttonEe.addActionListener(a);
       buttonR.addActionListener(a);
       buttonT.addActionListener(a);
       buttonY.addActionListener(a);
       buttonU.addActionListener(a);
       buttonI.addActionListener(a);
       buttonO.addActionListener(a);
       buttonP.addActionListener(a);
       buttonA.addActionListener(a);
       buttonS.addActionListener(a);
       buttonD.addActionListener(a);
       buttonF.addActionListener(a);
       buttonG.addActionListener(a);
       buttonH.addActionListener(a);
       buttonJ.addActionListener(a);
       buttonK.addActionListener(a);
       buttonL.addActionListener(a);
       buttonZ.addActionListener(a);
       buttonX.addActionListener(a);
       buttonC.addActionListener(a);
       bu.addActionListener(a);
       bb.addActionListener(a);
       bbb.addActionListener(a);
       bbbb.addActionListener(a);
       buttonV.addActionListener(a);
       buttonB.addActionListener(a);
       buttonN.addActionListener(a);
       buttonM.addActionListener(a);
       buttonESc.addActionListener(a);
       buttonE.addActionListener(a);
       buttonnnnn.addActionListener(a);
       buttonnnnnn.addActionListener(a);
       buttonnnnnnn.addActionListener(a);
       buttonnnnnnnn.addActionListener(a);
       but.addActionListener(a);
       butto.addActionListener(a);
       butt.addActionListener(a);
       bunn.addActionListener(a);
       b.addActionListener(a);
       buuu.addActionListener(a);
       bun.addActionListener(a);
       bt.addActionListener(a);
       
       
       button1.setToolTipText(" ! ");
       button2.setToolTipText(" @ ");
       button3.setToolTipText(" # ");
       button4.setToolTipText(" $ ");
       button5.setToolTipText(" % ");
       button6.setToolTipText(" ^ ");
       button7.setToolTipText(" & ");
       button8.setToolTipText(" * ");
       button9.setToolTipText(" ( ");
       button0.setToolTipText(" ) ");
       buttonn.setToolTipText(" _ ");
       buttonnnnnnnn.setToolTipText(" + ");
       buttonQ.setToolTipText(" َض ");
       buttonW.setToolTipText(" ص ");
       buttonEe.setToolTipText(" ث ");
       buttonR.setToolTipText(" ق ");
       buttonT.setToolTipText(" ف ");
       buttonY.setToolTipText(" غ ");
       buttonU.setToolTipText(" ع ");
       buttonI.setToolTipText(" ه");
       buttonO.setToolTipText(" خ ");
       buttonP.setToolTipText(" ح ");
       buttonA.setToolTipText(" ش ");
       buttonS.setToolTipText(" س ");
       buttonD.setToolTipText(" ي ");
       buttonF.setToolTipText(" ب ");
       buttonG.setToolTipText(" ل ");
       buttonH.setToolTipText(" ا ");
       buttonJ.setToolTipText(" ت ");
       buttonK.setToolTipText(" ن");
       buttonL.setToolTipText(" م ");
       buttonZ.setToolTipText(" ئ");
       buttonX.setToolTipText(" ء ");
       buttonC.setToolTipText(" ؤ ");
       buttonV.setToolTipText(" ر ");
       buttonB.setToolTipText(" لا ");
       buttonN.setToolTipText(" ى ");
       buttonM.setToolTipText(" ة ");
          
       Container c=fram.getContentPane();
       
       textarea.setBackground(Color.BLACK);
       textarea.setForeground(Color.WHITE);
       buttonESc.setBackground(Color.BLACK);
       buttonESc.setForeground(Color.WHITE);
       buttonE.setBackground(Color.BLACK);
       buttonE.setForeground(Color.WHITE);
       button1.setBackground(Color.BLACK);
       button1.setForeground(Color.WHITE);
       button2.setBackground(Color.BLACK);
       button2.setForeground(Color.WHITE);
       button3.setBackground(Color.BLACK);
       button3.setForeground(Color.WHITE);
       button4.setBackground(Color.BLACK);
       button4.setForeground(Color.WHITE);
       button5.setBackground(Color.BLACK);
       button5.setForeground(Color.WHITE);
       button6.setBackground(Color.BLACK);
       button6.setForeground(Color.WHITE);
       button7.setBackground(Color.BLACK);
       button7.setForeground(Color.WHITE);
       button8.setBackground(Color.BLACK);
       button8.setForeground(Color.WHITE);
       button9.setBackground(Color.BLACK);
       button9.setForeground(Color.WHITE);
       button0.setBackground(Color.BLACK);
       button0.setForeground(Color.WHITE);
       buttonn.setBackground(Color.BLACK);
       buttonn.setForeground(Color.WHITE);
       buttonnnn.setBackground(Color.BLACK);
       buttonnnn.setForeground(Color.WHITE);
       buttonnnnn.setBackground(Color.BLACK);
       buttonnnnn.setForeground(Color.WHITE);
       buttonnnnnn.setBackground(Color.BLACK);
       buttonnnnnn.setForeground(Color.WHITE);
       buttonnnnnnn.setBackground(Color.BLACK);
       buttonnnnnnn.setForeground(Color.WHITE);
       buttonnnnnnnn.setBackground(Color.BLACK);
       buttonnnnnnnn.setForeground(Color.WHITE);
       buttonHome.setBackground(Color.BLACK);
       buttonHome.setForeground(Color.WHITE);
       buttonPgUp.setBackground(Color.BLACK);
       buttonPgUp.setForeground(Color.WHITE);
       buttonNav.setBackground(Color.BLACK);
       buttonNav.setForeground(Color.WHITE);
       buttonEnd.setBackground(Color.BLACK);
       buttonEnd.setForeground(Color.WHITE);
       buttonPgDn.setBackground(Color.BLACK);
       buttonPgDn.setForeground(Color.WHITE);
       buttonMvUp.setBackground(Color.BLACK);
       buttonMvUp.setForeground(Color.WHITE);
       buttonInsert.setBackground(Color.BLACK);
       buttonInsert.setForeground(Color.WHITE);
       buttonPause.setBackground(Color.BLACK);
       buttonPause.setForeground(Color.WHITE);
       buttonMvDn.setBackground(Color.BLACK);
       buttonMvDn.setForeground(Color.WHITE);
       buttonPrtScn.setBackground(Color.BLACK);
       buttonPrtScn.setForeground(Color.WHITE);
       buttonScrlK.setBackground(Color.BLACK);
       buttonScrlK.setForeground(Color.WHITE);
       buttonDocK.setBackground(Color.BLACK);
       buttonDocK.setForeground(Color.WHITE);
       buttonOptions.setBackground(Color.BLACK);
       buttonOptions.setForeground(Color.WHITE);
       buttonHelp.setBackground(Color.BLACK);
       buttonHelp.setForeground(Color.WHITE);
       buttonFade.setBackground(Color.BLACK);
       buttonFade.setForeground(Color.WHITE);
       buttontab.setBackground(Color.BLACK);
       buttontab.setForeground(Color.WHITE);
       buttonQ.setBackground(Color.BLACK);
       buttonQ.setForeground(Color.WHITE);
       buttonW.setBackground(Color.BLACK);
       buttonW.setForeground(Color.WHITE);
       buttonE.setBackground(Color.BLACK);
       buttonE.setForeground(Color.WHITE);
       buttonR.setBackground(Color.BLACK);
       buttonR.setForeground(Color.WHITE);
       buttonT.setBackground(Color.BLACK);
       buttonT.setForeground(Color.WHITE);
       buttonY.setBackground(Color.BLACK);
       buttonY.setForeground(Color.WHITE);
       buttonU.setBackground(Color.BLACK);
       buttonU.setForeground(Color.WHITE);
       buttonI.setBackground(Color.BLACK);
       buttonI.setForeground(Color.WHITE);
       buttonO.setBackground(Color.BLACK);
       buttonO.setForeground(Color.WHITE);
       buttonP.setBackground(Color.BLACK);
       buttonP.setForeground(Color.WHITE);
       butto.setBackground(Color.BLACK);
       butto.setForeground(Color.WHITE);
       butt.setBackground(Color.BLACK);
       butt.setForeground(Color.WHITE);
       but.setBackground(Color.BLACK);
       but.setForeground(Color.WHITE);
       buttonCapslock.setBackground(Color.BLACK);
       buttonCapslock.setForeground(Color.WHITE);
       buttonA.setBackground(Color.BLACK);
       buttonA.setForeground(Color.WHITE);
       buttonS.setBackground(Color.BLACK);
       buttonS.setForeground(Color.WHITE);
       buttonD.setBackground(Color.BLACK);
       buttonD.setForeground(Color.WHITE);
       buttonF.setBackground(Color.BLACK);
       buttonF.setForeground(Color.WHITE);
       buttonG.setBackground(Color.BLACK);
       buttonG.setForeground(Color.WHITE);
       buttonH.setBackground(Color.BLACK);
       buttonH.setForeground(Color.WHITE);
       buttonJ.setBackground(Color.BLACK);
       buttonJ.setForeground(Color.WHITE);
       buttonK.setBackground(Color.BLACK);
       buttonK.setForeground(Color.WHITE);
       buttonL.setBackground(Color.BLACK);
       buttonL.setForeground(Color.WHITE);
       bu.setBackground(Color.BLACK);
       bu.setForeground(Color.WHITE);
       b.setBackground(Color.BLACK);
       b.setForeground(Color.WHITE);
       buttonenter.setBackground(Color.BLACK);
       buttonenter.setForeground(Color.WHITE);
       buttonshift.setBackground(Color.BLACK);
       buttonshift.setForeground(Color.WHITE);
       buttonZ.setBackground(Color.BLACK);
       buttonZ.setForeground(Color.WHITE);
       buttonX.setBackground(Color.BLACK);
       buttonX.setForeground(Color.WHITE);
       buttonC.setBackground(Color.BLACK);
       buttonC.setForeground(Color.WHITE);
       buttonV.setBackground(Color.BLACK);
       buttonV.setForeground(Color.WHITE);
       buttonB.setBackground(Color.BLACK);
       buttonB.setForeground(Color.WHITE);
       buttonN.setBackground(Color.BLACK);
       buttonN.setForeground(Color.WHITE);
       buttonM.setBackground(Color.BLACK);
       buttonM.setForeground(Color.WHITE);
       bb.setBackground(Color.BLACK);
       bb.setForeground(Color.WHITE);
        bbb.setBackground(Color.BLACK);
       bbb.setForeground(Color.WHITE);
       bbbb.setBackground(Color.BLACK);
       bbbb.setForeground(Color.WHITE);
       buttonshift.setBackground(Color.BLACK);
       buttonshift.setForeground(Color.WHITE);
       bun.setBackground(Color.BLACK);
       bun.setForeground(Color.WHITE);
       buttonCtrl.setBackground(Color.BLACK);
       buttonCtrl.setForeground(Color.WHITE);
       buttonFn.setBackground(Color.BLACK);
       buttonFn.setForeground(Color.WHITE);
       buttonalt.setBackground(Color.BLACK);
       buttonalt.setForeground(Color.WHITE);
       buu.setBackground(Color.BLACK);
       buu.setForeground(Color.WHITE);
       buttonAlt.setBackground(Color.BLACK);
       buttonAlt.setForeground(Color.WHITE);
       buttonctrl.setBackground(Color.BLACK);
       buttonctrl.setForeground(Color.WHITE);
       buuu.setBackground(Color.BLACK);
       buuu.setForeground(Color.WHITE);
       bunn.setBackground(Color.BLACK);
       bunn.setForeground(Color.WHITE);
       buttonbackspace.setBackground(Color.BLACK);
       buttonbackspace.setForeground(Color.WHITE);
       buttonShift.setBackground(Color.BLACK);
       buttonShift.setForeground(Color.WHITE);
       buttonEe.setBackground(Color.BLACK);
       buttonEe.setForeground(Color.WHITE);
       buttonDel.setBackground(Color.BLACK);
       buttonDel.setForeground(Color.WHITE);
       bt.setBackground(Color.BLACK);
       bt.setForeground(Color.WHITE);
       bnnn.setBackground(Color.BLACK);
       bnnn.setForeground(Color.WHITE);
       
       fram.setLayout(new BorderLayout());
      c.add(textarea,BorderLayout.NORTH);
   panel.setLayout(new FlowLayout(FlowLayout.LEFT,0,0));
   panel.add(buttonESc);
   panel.add(b);
   panel.add(button1);
   panel.add(button2);
   panel.add(button3);
   panel.add(button4);
   panel.add(button5);
   panel.add(button6);
   panel.add(button7);
   panel.add(button8);
   panel.add(button9);
   panel.add(button0);
   panel.add(buttonn);
   panel.add(buttonnnnnnnn);
   panel.add(buttonbackspace);
   panel.add(buttontab);
   panel.add(buttonQ);
   panel.add(buttonW);
   panel.add(buttonEe);
   panel.add(buttonR);
   panel.add(buttonT);
   panel.add(buttonY);
   panel.add(buttonU);
   panel.add(buttonI);
   panel.add(buttonO);
   panel.add(buttonP);
   panel.add(butto);
   panel.add(butt);
   panel.add(but);
   panel.add(buttonDel);
   panel.add(buttonCapslock);
   panel.add(buttonA);
   panel.add(buttonS);
   panel.add(buttonD);
   panel.add(buttonF);
   panel.add(buttonG);
   panel.add(buttonH);
   panel.add(buttonJ);
   panel.add(buttonK);
   panel.add(buttonL);
   panel.add(bu);
   panel.add(bt);
   panel.add(buttonenter);
   panel.add(buttonshift);
   panel.add(buttonZ);
   panel.add(buttonX);
   panel.add(buttonC);
   panel.add(buttonV);
   panel.add(buttonB);
   panel.add(buttonN);
   panel.add(buttonM);
   panel.add(bb);
   panel.add(bbb);
   panel.add(bbbb);
   panel.add(bun);
   panel.add(buttonShift);
   panel.add(buttonctrl);
   panel.add(buttonFn);
   panel.add(buttonalt);
   panel.add(buu);
   panel.add(buttonAlt);
   panel.add(bnnn);
   panel.add(buttonCtrl);
   panel.add(buuu);
   panel.add(bunn);
   panel.add(buttonnnn);
   panel.add(buttonnnnnn);
   panel.add(buttonnnnnnn);
   c.add(panel, BorderLayout.CENTER);
   panel1.setLayout(new GridLayout(5,3));
   panel1.add(buttonHome);
   panel1.add(buttonPgUp);
   panel1.add(buttonNav);
   panel1.add(buttonEnd);
   panel1.add(buttonPgDn);
   panel1.add(buttonMvUp);
   panel1.add(buttonInsert);
   panel1.add(buttonPause);
   panel1.add(buttonMvDn);
   panel1.add(buttonPrtScn);
   panel1.add(buttonScrlK);
   panel1.add(buttonDocK);
   panel1.add(buttonOptions);
   panel1.add(buttonHelp);
   panel1.add(buttonFade);
   c.add(panel1, BorderLayout.EAST);
      fram.setSize(930, 200);
      fram.setVisible(true);
      fram.setDefaultCloseOperation(fram.EXIT_ON_CLOSE);
    }
  public class myaction implements ActionListener{
        public void actionPerformed(ActionEvent e){
        if(cap == true)
            textarea.append(e.getActionCommand().toUpperCase()); 
        else
            textarea.append(e.getActionCommand()); 
    }}
  public class myaction2 implements ActionListener{
        public void actionPerformed(ActionEvent e) {
            textarea.append("      ");  
        }}
   public class myaction3 implements ActionListener{
        String []s={"a","b","c","d","e","f","g","h","i","j","k","l","m","n","o","p","q","r","s","t","u","v","w","x","y","z"};
       String s1="";
       //cap=false;
    public void actionPerformed(ActionEvent e) {
      if(e.getSource()==buttonDel){
                    String f=textarea.getText();
         textarea.setText("");
      }else if(e.getSource()==buttonCapslock){
              cap = !cap;
             for(int i=0;i<26;i++){
              if(e.getActionCommand()==s[i]){
                   if(cap==false){
                            s1+=s[i].toLowerCase();
                   }else{
                            s1+=s[i].toUpperCase();
                   }
                   if(cap==false){
                        textarea.append(e.getActionCommand().toLowerCase());
                   }else{    
                            textarea.append(e.getActionCommand().toUpperCase());
                        }
                        break;
                    }}
     }else if(e.getSource()==buttonenter){
            textarea.append("\n");
     }else if(e.getSource()==buu){ 
            textarea.append("  ");
     }else if(e.getSource()==buttonHome){
                textarea.setCaretPosition(0);
                textarea.requestFocus();
     }else if(e.getSource()==buttonbackspace){
                String text = textarea.getText();
                int size=text.length()-1;
                 textarea.setText(text.substring(0, size));
    }else if(e.getSource()==buttontab){
             textarea.append("      ");
    }
    }}
}
class test{
    public static void main(String[] args) {
        Keyboard c=new Keyboard();
    }
}
